#!/bin/bash
echo "🔍 GitHub Actions Build Status Check"
echo "======================================"
echo ""
echo "Repository: aka209859-max/gym-tracker-flutter"
echo "Latest Tag: v1.0.261"
echo "Build URL: https://github.com/aka209859-max/gym-tracker-flutter/actions"
echo ""
echo "⚠️ Build failed with exit code 1"
echo "⚠️ Multiple SwiftPreview warnings detected"
echo ""
echo "Next Steps:"
echo "1. Check full GitHub Actions logs at URL above"
echo "2. Look for actual error (not just SwiftPreview warnings)"
echo "3. Common issues:"
echo "   - Code signing problems"
echo "   - Missing dependencies"
echo "   - Build configuration errors"
echo "   - Xcode compatibility issues"
