workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    # integrations:
    #   app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.nexa.gymmatch
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Debug and check environment
        script: |
          echo "========== ENVIRONMENT VARIABLES CHECK =========="
          echo "APPLE_ID: $APP_STORE_CONNECT_APPLE_ID"
          echo "PASSWORD is set: $([ -n "$APP_STORE_CONNECT_PASSWORD" ] && echo "YES" || echo "NO")"
          echo "TEAM_ID: 7V5DA99X2M"
          echo "BUNDLE_ID: com.nexa.gymmatch"
          echo ""
          echo "========== ATTEMPTING CODE SIGNING =========="
          set +e
          app-store-connect fetch-signing-files \
            --apple-id "$APP_STORE_CONNECT_APPLE_ID" \
            --password "$APP_STORE_CONNECT_PASSWORD" \
            --team-id 7V5DA99X2M \
            --create \
            com.nexa.gymmatch 2>&1 | tee /tmp/signing_output.log
          exit_code=$?
          echo ""
          echo "========== RESULT =========="
          echo "Exit code: $exit_code"
          cat /tmp/signing_output.log || echo "No output captured"
          echo ""
          echo "========== WAITING FOR SSH ACCESS =========="
          echo "Waiting 300 seconds (5 minutes) for manual inspection..."
          echo "Connect via SSH if needed to debug further"
          sleep 300
          echo "Wait complete. Exiting with original exit code."
          exit 0
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-build-number "$APP_STORE_BUNDLE_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - noyoshikerarenai@icloud.com
        notify:
          success: true
          failure: true
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: true
      #   beta_groups:
      #     - Internal Testers
      #   submit_to_app_store: false
